// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: response_show_bracket_stops.proto

package order

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResponseShowBracketStops struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId               *int32   `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                              // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg                  []string `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                        // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode          []string `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`                            // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode                   []string `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                                           // PB_OFFSET + MNM_RESPONSE_CODE
	BasketId                 *string  `protobuf:"bytes,110300,opt,name=basket_id,json=basketId" json:"basket_id,omitempty"`                                                     // PB_OFFSET + MNM_BASKET_ID
	StopQuantity             *string  `protobuf:"bytes,154459,opt,name=stop_quantity,json=stopQuantity" json:"stop_quantity,omitempty"`                                         // PB_OFFSET + MNM_STOP_QUANTITY
	StopQuantityReleased     *string  `protobuf:"bytes,154466,opt,name=stop_quantity_released,json=stopQuantityReleased" json:"stop_quantity_released,omitempty"`               // PB_OFFSET + MNM_STOP_QUANTITY_RELEASED
	StopTicks                *string  `protobuf:"bytes,154458,opt,name=stop_ticks,json=stopTicks" json:"stop_ticks,omitempty"`                                                  // PB_OFFSET + MNM_STOP_TICKS
	BracketTrailingFieldId   *string  `protobuf:"bytes,157062,opt,name=bracket_trailing_field_id,json=bracketTrailingFieldId" json:"bracket_trailing_field_id,omitempty"`       // PB_OFFSET + MNM_BRACKET_TRAILING_FIELD_ID
	TrailingStopTriggerTicks *string  `protobuf:"bytes,157124,opt,name=trailing_stop_trigger_ticks,json=trailingStopTriggerTicks" json:"trailing_stop_trigger_ticks,omitempty"` // PB_OFFSET + MNM_TRAILING_STOP_TRIGGER_TICKS
}

func (x *ResponseShowBracketStops) Reset() {
	*x = ResponseShowBracketStops{}
	if protoimpl.UnsafeEnabled {
		mi := &file_response_show_bracket_stops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseShowBracketStops) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseShowBracketStops) ProtoMessage() {}

func (x *ResponseShowBracketStops) ProtoReflect() protoreflect.Message {
	mi := &file_response_show_bracket_stops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseShowBracketStops.ProtoReflect.Descriptor instead.
func (*ResponseShowBracketStops) Descriptor() ([]byte, []int) {
	return file_response_show_bracket_stops_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseShowBracketStops) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseShowBracketStops) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseShowBracketStops) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseShowBracketStops) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseShowBracketStops) GetBasketId() string {
	if x != nil && x.BasketId != nil {
		return *x.BasketId
	}
	return ""
}

func (x *ResponseShowBracketStops) GetStopQuantity() string {
	if x != nil && x.StopQuantity != nil {
		return *x.StopQuantity
	}
	return ""
}

func (x *ResponseShowBracketStops) GetStopQuantityReleased() string {
	if x != nil && x.StopQuantityReleased != nil {
		return *x.StopQuantityReleased
	}
	return ""
}

func (x *ResponseShowBracketStops) GetStopTicks() string {
	if x != nil && x.StopTicks != nil {
		return *x.StopTicks
	}
	return ""
}

func (x *ResponseShowBracketStops) GetBracketTrailingFieldId() string {
	if x != nil && x.BracketTrailingFieldId != nil {
		return *x.BracketTrailingFieldId
	}
	return ""
}

func (x *ResponseShowBracketStops) GetTrailingStopTriggerTicks() string {
	if x != nil && x.TrailingStopTriggerTicks != nil {
		return *x.TrailingStopTriggerTicks
	}
	return ""
}

var File_response_show_bracket_stops_proto protoreflect.FileDescriptor

var file_response_show_bracket_stops_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x68, 0x6f, 0x77, 0x5f,
	0x62, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x74, 0x69, 0x22, 0xc1, 0x03, 0x0a, 0x18, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x42, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x21, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x98, 0x8d, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x71, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x9c, 0x8d, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x71, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x9e, 0x8d, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1d, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0xdc, 0xdd, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0xdb, 0xb6, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x16, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18,
	0xe2, 0xb6, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x73, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x12, 0x1f, 0x0a,
	0x0a, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x18, 0xda, 0xb6, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x3b,
	0x0a, 0x19, 0x62, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x69,
	0x6e, 0x67, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x86, 0xcb, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x16, 0x62, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69,
	0x6c, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x1b, 0x74,
	0x72, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x18, 0xc4, 0xcb, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x18, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x70,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x73,
}

var (
	file_response_show_bracket_stops_proto_rawDescOnce sync.Once
	file_response_show_bracket_stops_proto_rawDescData = file_response_show_bracket_stops_proto_rawDesc
)

func file_response_show_bracket_stops_proto_rawDescGZIP() []byte {
	file_response_show_bracket_stops_proto_rawDescOnce.Do(func() {
		file_response_show_bracket_stops_proto_rawDescData = protoimpl.X.CompressGZIP(file_response_show_bracket_stops_proto_rawDescData)
	})
	return file_response_show_bracket_stops_proto_rawDescData
}

var file_response_show_bracket_stops_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_show_bracket_stops_proto_goTypes = []interface{}{
	(*ResponseShowBracketStops)(nil), // 0: rti.ResponseShowBracketStops
}
var file_response_show_bracket_stops_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_show_bracket_stops_proto_init() }
func file_response_show_bracket_stops_proto_init() {
	if File_response_show_bracket_stops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_response_show_bracket_stops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseShowBracketStops); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_response_show_bracket_stops_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_show_bracket_stops_proto_goTypes,
		DependencyIndexes: file_response_show_bracket_stops_proto_depIdxs,
		MessageInfos:      file_response_show_bracket_stops_proto_msgTypes,
	}.Build()
	File_response_show_bracket_stops_proto = out.File
	file_response_show_bracket_stops_proto_rawDesc = nil
	file_response_show_bracket_stops_proto_goTypes = nil
	file_response_show_bracket_stops_proto_depIdxs = nil
}
