// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: order_book.proto

package rti

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// below enum is just for reference only, not used in this message
type OrderBook_PresenceBits int32

const (
	OrderBook_BID OrderBook_PresenceBits = 1
	OrderBook_ASK OrderBook_PresenceBits = 2
)

// Enum value maps for OrderBook_PresenceBits.
var (
	OrderBook_PresenceBits_name = map[int32]string{
		1: "BID",
		2: "ASK",
	}
	OrderBook_PresenceBits_value = map[string]int32{
		"BID": 1,
		"ASK": 2,
	}
)

func (x OrderBook_PresenceBits) Enum() *OrderBook_PresenceBits {
	p := new(OrderBook_PresenceBits)
	*p = x
	return p
}

func (x OrderBook_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBook_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_order_book_proto_enumTypes[0].Descriptor()
}

func (OrderBook_PresenceBits) Type() protoreflect.EnumType {
	return &file_order_book_proto_enumTypes[0]
}

func (x OrderBook_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrderBook_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrderBook_PresenceBits(num)
	return nil
}

// Deprecated: Use OrderBook_PresenceBits.Descriptor instead.
func (OrderBook_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0, 0}
}

type OrderBook_UpdateType int32

const (
	OrderBook_CLEAR_ORDER_BOOK OrderBook_UpdateType = 1
	OrderBook_NO_BOOK          OrderBook_UpdateType = 2
	OrderBook_SNAPSHOT_IMAGE   OrderBook_UpdateType = 3
	OrderBook_BEGIN            OrderBook_UpdateType = 4
	OrderBook_MIDDLE           OrderBook_UpdateType = 5
	OrderBook_END              OrderBook_UpdateType = 6
	OrderBook_SOLO             OrderBook_UpdateType = 7
)

// Enum value maps for OrderBook_UpdateType.
var (
	OrderBook_UpdateType_name = map[int32]string{
		1: "CLEAR_ORDER_BOOK",
		2: "NO_BOOK",
		3: "SNAPSHOT_IMAGE",
		4: "BEGIN",
		5: "MIDDLE",
		6: "END",
		7: "SOLO",
	}
	OrderBook_UpdateType_value = map[string]int32{
		"CLEAR_ORDER_BOOK": 1,
		"NO_BOOK":          2,
		"SNAPSHOT_IMAGE":   3,
		"BEGIN":            4,
		"MIDDLE":           5,
		"END":              6,
		"SOLO":             7,
	}
)

func (x OrderBook_UpdateType) Enum() *OrderBook_UpdateType {
	p := new(OrderBook_UpdateType)
	*p = x
	return p
}

func (x OrderBook_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBook_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_book_proto_enumTypes[1].Descriptor()
}

func (OrderBook_UpdateType) Type() protoreflect.EnumType {
	return &file_order_book_proto_enumTypes[1]
}

func (x OrderBook_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrderBook_UpdateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrderBook_UpdateType(num)
	return nil
}

// Deprecated: Use OrderBook_UpdateType.Descriptor instead.
func (OrderBook_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0, 1}
}

type OrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId   *int32                `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                               // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol       *string               `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                          // PB_OFFSET + MNM_SYMBOL
	Exchange     *string               `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                      // PB_OFFSET + MNM_EXCHANGE
	PresenceBits *uint32               `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`                         // PB_OFFSET + MNM_PRICING_INDICATOR
	UpdateType   *OrderBook_UpdateType `protobuf:"varint,157608,opt,name=update_type,json=updateType,enum=rti.OrderBook_UpdateType" json:"update_type,omitempty"` // PB_OFFSET + MNM_MARKET_DEPTH_UPDATE_TYPE
	BidPrice     []float64             `protobuf:"fixed64,154282,rep,name=bid_price,json=bidPrice" json:"bid_price,omitempty"`                                    // PB_OFFSET + MNM_MARKET_DEPTH_BID_PRICE
	BidSize      []int32               `protobuf:"varint,154283,rep,name=bid_size,json=bidSize" json:"bid_size,omitempty"`                                        // PB_OFFSET + MNM_MARKET_DEPTH_BID_SIZE
	BidOrders    []int32               `protobuf:"varint,154401,rep,name=bid_orders,json=bidOrders" json:"bid_orders,omitempty"`                                  // PB_OFFSET + MNM_MARKET_DEPTH_BID_NO_OF_ORDERS
	ImplBidSize  []int32               `protobuf:"varint,154412,rep,name=impl_bid_size,json=implBidSize" json:"impl_bid_size,omitempty"`                          // PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_BID_SIZE
	AskPrice     []float64             `protobuf:"fixed64,154284,rep,name=ask_price,json=askPrice" json:"ask_price,omitempty"`                                    // PB_OFFSET + MNM_MARKET_DEPTH_ASK_PRICE
	AskSize      []int32               `protobuf:"varint,154285,rep,name=ask_size,json=askSize" json:"ask_size,omitempty"`                                        // PB_OFFSET + MNM_MARKET_DEPTH_ASK_SIZE
	AskOrders    []int32               `protobuf:"varint,154402,rep,name=ask_orders,json=askOrders" json:"ask_orders,omitempty"`                                  // PB_OFFSET + MNM_MARKET_DEPTH_ASK_NO_OF_ORDERS
	ImplAskSize  []int32               `protobuf:"varint,154415,rep,name=impl_ask_size,json=implAskSize" json:"impl_ask_size,omitempty"`                          // PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_ASK_SIZE
	Ssboe        *int32                `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`                                                           // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs        *int32                `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`                                                           // PB_OFFSET + MNM_USECS
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_order_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBook) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *OrderBook) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *OrderBook) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *OrderBook) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *OrderBook) GetUpdateType() OrderBook_UpdateType {
	if x != nil && x.UpdateType != nil {
		return *x.UpdateType
	}
	return OrderBook_CLEAR_ORDER_BOOK
}

func (x *OrderBook) GetBidPrice() []float64 {
	if x != nil {
		return x.BidPrice
	}
	return nil
}

func (x *OrderBook) GetBidSize() []int32 {
	if x != nil {
		return x.BidSize
	}
	return nil
}

func (x *OrderBook) GetBidOrders() []int32 {
	if x != nil {
		return x.BidOrders
	}
	return nil
}

func (x *OrderBook) GetImplBidSize() []int32 {
	if x != nil {
		return x.ImplBidSize
	}
	return nil
}

func (x *OrderBook) GetAskPrice() []float64 {
	if x != nil {
		return x.AskPrice
	}
	return nil
}

func (x *OrderBook) GetAskSize() []int32 {
	if x != nil {
		return x.AskSize
	}
	return nil
}

func (x *OrderBook) GetAskOrders() []int32 {
	if x != nil {
		return x.AskOrders
	}
	return nil
}

func (x *OrderBook) GetImplAskSize() []int32 {
	if x != nil {
		return x.ImplAskSize
	}
	return nil
}

func (x *OrderBook) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *OrderBook) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_order_book_proto protoreflect.FileDescriptor

var file_order_book_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x72, 0x74, 0x69, 0x22, 0x92, 0x05, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x94, 0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x95,
	0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x25, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x62, 0x69, 0x74,
	0x73, 0x18, 0x92, 0x8d, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x42, 0x69, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0xa8, 0xcf, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x72, 0x74, 0x69, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x62, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0xaa, 0xb5, 0x09, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x62, 0x69, 0x64, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x62, 0x69, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0xab, 0xb5, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x62, 0x69, 0x64, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x69, 0x64, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18,
	0xa1, 0xb6, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x62, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6d, 0x70, 0x6c, 0x5f, 0x62, 0x69, 0x64, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0xac, 0xb6, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6d, 0x70,
	0x6c, 0x42, 0x69, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x61, 0x73, 0x6b, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0xac, 0xb5, 0x09, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x61,
	0x73, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x61, 0x73, 0x6b, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0xad, 0xb5, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x61, 0x73, 0x6b,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x61, 0x73, 0x6b, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x18, 0xa2, 0xb6, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x61, 0x73, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6d, 0x70, 0x6c, 0x5f, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0xaf, 0xb6, 0x09, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b,
	0x69, 0x6d, 0x70, 0x6c, 0x41, 0x73, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x73,
	0x73, 0x62, 0x6f, 0x65, 0x18, 0xd4, 0x94, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x73,
	0x62, 0x6f, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x63, 0x73, 0x18, 0xd5, 0x94, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x63, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x69, 0x74, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x42,
	0x49, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x4b, 0x10, 0x02, 0x22, 0x6d, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x43,
	0x4c, 0x45, 0x41, 0x52, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x42, 0x4f, 0x4f, 0x4b, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x5f, 0x49, 0x4d, 0x41, 0x47, 0x45,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x49, 0x44, 0x44, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x44,
	0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x4f, 0x4c, 0x4f, 0x10, 0x07,
}

var (
	file_order_book_proto_rawDescOnce sync.Once
	file_order_book_proto_rawDescData = file_order_book_proto_rawDesc
)

func file_order_book_proto_rawDescGZIP() []byte {
	file_order_book_proto_rawDescOnce.Do(func() {
		file_order_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_book_proto_rawDescData)
	})
	return file_order_book_proto_rawDescData
}

var file_order_book_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_book_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_book_proto_goTypes = []interface{}{
	(OrderBook_PresenceBits)(0), // 0: rti.OrderBook.PresenceBits
	(OrderBook_UpdateType)(0),   // 1: rti.OrderBook.UpdateType
	(*OrderBook)(nil),           // 2: rti.OrderBook
}
var file_order_book_proto_depIdxs = []int32{
	1, // 0: rti.OrderBook.update_type:type_name -> rti.OrderBook.UpdateType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_book_proto_init() }
func file_order_book_proto_init() {
	if File_order_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_book_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_book_proto_goTypes,
		DependencyIndexes: file_order_book_proto_depIdxs,
		EnumInfos:         file_order_book_proto_enumTypes,
		MessageInfos:      file_order_book_proto_msgTypes,
	}.Build()
	File_order_book_proto = out.File
	file_order_book_proto_rawDesc = nil
	file_order_book_proto_goTypes = nil
	file_order_book_proto_depIdxs = nil
}
