// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: symbol_margin_rate.proto

package rti

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SymbolMarginRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId *int32   `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`  // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol     *string  `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                             // PB_OFFSET + MNM_SYMBOL
	Exchange   *string  `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                         // PB_OFFSET + MNM_EXCHANGE
	IsSnapshot *bool    `protobuf:"varint,110121,opt,name=is_snapshot,json=isSnapshot" json:"is_snapshot,omitempty"`  // PB_OFFSET + MNM_UPDATE_TYPE
	MarginRate *float64 `protobuf:"fixed64,154103,opt,name=margin_rate,json=marginRate" json:"margin_rate,omitempty"` // PB_OFFSET + MNM_MARGIN_RATE
}

func (x *SymbolMarginRate) Reset() {
	*x = SymbolMarginRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbol_margin_rate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolMarginRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolMarginRate) ProtoMessage() {}

func (x *SymbolMarginRate) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_margin_rate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolMarginRate.ProtoReflect.Descriptor instead.
func (*SymbolMarginRate) Descriptor() ([]byte, []int) {
	return file_symbol_margin_rate_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolMarginRate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *SymbolMarginRate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *SymbolMarginRate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *SymbolMarginRate) GetIsSnapshot() bool {
	if x != nil && x.IsSnapshot != nil {
		return *x.IsSnapshot
	}
	return false
}

func (x *SymbolMarginRate) GetMarginRate() float64 {
	if x != nil && x.MarginRate != nil {
		return *x.MarginRate
	}
	return 0
}

var File_symbol_margin_rate_proto protoreflect.FileDescriptor

var file_symbol_margin_rate_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x74, 0x69, 0x22,
	0xb3, 0x01, 0x0a, 0x10, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x94, 0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x95, 0xdc,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0xa9,
	0xdc, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x61, 0x74,
	0x65, 0x18, 0xf7, 0xb3, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x52, 0x61, 0x74, 0x65,
}

var (
	file_symbol_margin_rate_proto_rawDescOnce sync.Once
	file_symbol_margin_rate_proto_rawDescData = file_symbol_margin_rate_proto_rawDesc
)

func file_symbol_margin_rate_proto_rawDescGZIP() []byte {
	file_symbol_margin_rate_proto_rawDescOnce.Do(func() {
		file_symbol_margin_rate_proto_rawDescData = protoimpl.X.CompressGZIP(file_symbol_margin_rate_proto_rawDescData)
	})
	return file_symbol_margin_rate_proto_rawDescData
}

var file_symbol_margin_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_symbol_margin_rate_proto_goTypes = []interface{}{
	(*SymbolMarginRate)(nil), // 0: rti.SymbolMarginRate
}
var file_symbol_margin_rate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symbol_margin_rate_proto_init() }
func file_symbol_margin_rate_proto_init() {
	if File_symbol_margin_rate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symbol_margin_rate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolMarginRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symbol_margin_rate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_symbol_margin_rate_proto_goTypes,
		DependencyIndexes: file_symbol_margin_rate_proto_depIdxs,
		MessageInfos:      file_symbol_margin_rate_proto_msgTypes,
	}.Build()
	File_symbol_margin_rate_proto = out.File
	file_symbol_margin_rate_proto_rawDesc = nil
	file_symbol_margin_rate_proto_goTypes = nil
	file_symbol_margin_rate_proto_depIdxs = nil
}
