// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: front_month_contract_update.proto

package market

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FrontMonthContractUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId         *int32  `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                             // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol             *string `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                        // PB_OFFSET + MNM_SYMBOL
	Exchange           *string `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                    // PB_OFFSET + MNM_EXCHANGE
	IsFrontMonthSymbol *bool   `protobuf:"varint,149166,opt,name=is_front_month_symbol,json=isFrontMonthSymbol" json:"is_front_month_symbol,omitempty"` // PB_OFFSET + MNM_STATUS_INDICATOR
	SymbolName         *string `protobuf:"bytes,100003,opt,name=symbol_name,json=symbolName" json:"symbol_name,omitempty"`                              // PB_OFFSET + MNM_SYMBOL_NAME
	TradingSymbol      *string `protobuf:"bytes,157095,opt,name=trading_symbol,json=tradingSymbol" json:"trading_symbol,omitempty"`                     // PB_OFFSET + MNM_TRADING_SYMBOL
	TradingExchange    *string `protobuf:"bytes,157096,opt,name=trading_exchange,json=tradingExchange" json:"trading_exchange,omitempty"`               // PB_OFFSET + MNM_TRADING_EXCHANGE
}

func (x *FrontMonthContractUpdate) Reset() {
	*x = FrontMonthContractUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_front_month_contract_update_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrontMonthContractUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontMonthContractUpdate) ProtoMessage() {}

func (x *FrontMonthContractUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_front_month_contract_update_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontMonthContractUpdate.ProtoReflect.Descriptor instead.
func (*FrontMonthContractUpdate) Descriptor() ([]byte, []int) {
	return file_front_month_contract_update_proto_rawDescGZIP(), []int{0}
}

func (x *FrontMonthContractUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *FrontMonthContractUpdate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *FrontMonthContractUpdate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *FrontMonthContractUpdate) GetIsFrontMonthSymbol() bool {
	if x != nil && x.IsFrontMonthSymbol != nil {
		return *x.IsFrontMonthSymbol
	}
	return false
}

func (x *FrontMonthContractUpdate) GetSymbolName() string {
	if x != nil && x.SymbolName != nil {
		return *x.SymbolName
	}
	return ""
}

func (x *FrontMonthContractUpdate) GetTradingSymbol() string {
	if x != nil && x.TradingSymbol != nil {
		return *x.TradingSymbol
	}
	return ""
}

func (x *FrontMonthContractUpdate) GetTradingExchange() string {
	if x != nil && x.TradingExchange != nil {
		return *x.TradingExchange
	}
	return ""
}

var File_front_month_contract_update_proto protoreflect.FileDescriptor

var file_front_month_contract_update_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x74, 0x69, 0x22, 0xa3, 0x02, 0x0a, 0x18, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x94, 0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x95,
	0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x33, 0x0a, 0x15, 0x69, 0x73, 0x5f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0xae, 0x8d, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x69, 0x73, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0xa3, 0x8d, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0xa7, 0xcb, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x2b, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0xa8, 0xcb, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
}

var (
	file_front_month_contract_update_proto_rawDescOnce sync.Once
	file_front_month_contract_update_proto_rawDescData = file_front_month_contract_update_proto_rawDesc
)

func file_front_month_contract_update_proto_rawDescGZIP() []byte {
	file_front_month_contract_update_proto_rawDescOnce.Do(func() {
		file_front_month_contract_update_proto_rawDescData = protoimpl.X.CompressGZIP(file_front_month_contract_update_proto_rawDescData)
	})
	return file_front_month_contract_update_proto_rawDescData
}

var file_front_month_contract_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_front_month_contract_update_proto_goTypes = []interface{}{
	(*FrontMonthContractUpdate)(nil), // 0: rti.FrontMonthContractUpdate
}
var file_front_month_contract_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_front_month_contract_update_proto_init() }
func file_front_month_contract_update_proto_init() {
	if File_front_month_contract_update_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_front_month_contract_update_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrontMonthContractUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_front_month_contract_update_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_front_month_contract_update_proto_goTypes,
		DependencyIndexes: file_front_month_contract_update_proto_depIdxs,
		MessageInfos:      file_front_month_contract_update_proto_msgTypes,
	}.Build()
	File_front_month_contract_update_proto = out.File
	file_front_month_contract_update_proto_rawDesc = nil
	file_front_month_contract_update_proto_goTypes = nil
	file_front_month_contract_update_proto_depIdxs = nil
}
