// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: request_product_codes.proto

package market

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestProductCodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId          *int32   `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg             []string `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                          // PB_OFFSET + MNM_USER_MSG
	Exchange            *string  `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                       // PB_OFFSET + MNM_EXCHANGE
	GiveToiProductsOnly *bool    `protobuf:"varint,153499,opt,name=give_toi_products_only,json=giveToiProductsOnly" json:"give_toi_products_only,omitempty"` // PB_OFFSET + MNM_TOI_PRODUCTS_ONLY
}

func (x *RequestProductCodes) Reset() {
	*x = RequestProductCodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_product_codes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestProductCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductCodes) ProtoMessage() {}

func (x *RequestProductCodes) ProtoReflect() protoreflect.Message {
	mi := &file_request_product_codes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductCodes.ProtoReflect.Descriptor instead.
func (*RequestProductCodes) Descriptor() ([]byte, []int) {
	return file_request_product_codes_proto_rawDescGZIP(), []int{0}
}

func (x *RequestProductCodes) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestProductCodes) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestProductCodes) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestProductCodes) GetGiveToiProductsOnly() bool {
	if x != nil && x.GiveToiProductsOnly != nil {
		return *x.GiveToiProductsOnly
	}
	return false
}

var File_request_product_codes_proto protoreflect.FileDescriptor

var file_request_product_codes_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72,
	0x74, 0x69, 0x22, 0xaa, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0b, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x98, 0x8d, 0x08, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x95, 0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x16, 0x67, 0x69, 0x76, 0x65,
	0x5f, 0x74, 0x6f, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x5f, 0x6f, 0x6e,
	0x6c, 0x79, 0x18, 0x9b, 0xaf, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x67, 0x69, 0x76, 0x65,
	0x54, 0x6f, 0x69, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x4f, 0x6e, 0x6c, 0x79,
}

var (
	file_request_product_codes_proto_rawDescOnce sync.Once
	file_request_product_codes_proto_rawDescData = file_request_product_codes_proto_rawDesc
)

func file_request_product_codes_proto_rawDescGZIP() []byte {
	file_request_product_codes_proto_rawDescOnce.Do(func() {
		file_request_product_codes_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_product_codes_proto_rawDescData)
	})
	return file_request_product_codes_proto_rawDescData
}

var file_request_product_codes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_product_codes_proto_goTypes = []interface{}{
	(*RequestProductCodes)(nil), // 0: rti.RequestProductCodes
}
var file_request_product_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_product_codes_proto_init() }
func file_request_product_codes_proto_init() {
	if File_request_product_codes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_request_product_codes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestProductCodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_product_codes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_product_codes_proto_goTypes,
		DependencyIndexes: file_request_product_codes_proto_depIdxs,
		MessageInfos:      file_request_product_codes_proto_msgTypes,
	}.Build()
	File_request_product_codes_proto = out.File
	file_request_product_codes_proto_rawDesc = nil
	file_request_product_codes_proto_goTypes = nil
	file_request_product_codes_proto_depIdxs = nil
}
