// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: response_product_codes.proto

package market

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResponseProductCodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId             *int32   `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                           // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg                []string `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                     // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode        []string `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`                         // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode                 []string `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                                        // PB_OFFSET + MNM_RESPONSE_CODE
	Exchange               *string  `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                                  // PB_OFFSET + MNM_EXCHANGE
	SymbolName             *string  `protobuf:"bytes,100003,opt,name=symbol_name,json=symbolName" json:"symbol_name,omitempty"`                                            // PB_OFFSET + MNM_SYMBOL_NAME
	ProductCode            *string  `protobuf:"bytes,100749,opt,name=product_code,json=productCode" json:"product_code,omitempty"`                                         // PB_OFFSET + MNM_PRODUCT_CODE
	TimezoneTimeOfInterest *string  `protobuf:"bytes,154682,opt,name=timezone_time_of_interest,json=timezoneTimeOfInterest" json:"timezone_time_of_interest,omitempty"`    // PB_OFFSET + MNM_TIMEZONE_TIME_OF_INTEREST
	BeginTimeOfInterestMsm *int32   `protobuf:"varint,154680,opt,name=begin_time_of_interest_msm,json=beginTimeOfInterestMsm" json:"begin_time_of_interest_msm,omitempty"` // PB_OFFSET + MNM_BEGIN_TIME_OF_INTEREST_MSM
	EndTimeOfInterestMsm   *int32   `protobuf:"varint,154681,opt,name=end_time_of_interest_msm,json=endTimeOfInterestMsm" json:"end_time_of_interest_msm,omitempty"`       // PB_OFFSET + MNM_END_TIME_OF_INTEREST_MSM
}

func (x *ResponseProductCodes) Reset() {
	*x = ResponseProductCodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_response_product_codes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseProductCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseProductCodes) ProtoMessage() {}

func (x *ResponseProductCodes) ProtoReflect() protoreflect.Message {
	mi := &file_response_product_codes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseProductCodes.ProtoReflect.Descriptor instead.
func (*ResponseProductCodes) Descriptor() ([]byte, []int) {
	return file_response_product_codes_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseProductCodes) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseProductCodes) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseProductCodes) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseProductCodes) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseProductCodes) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ResponseProductCodes) GetSymbolName() string {
	if x != nil && x.SymbolName != nil {
		return *x.SymbolName
	}
	return ""
}

func (x *ResponseProductCodes) GetProductCode() string {
	if x != nil && x.ProductCode != nil {
		return *x.ProductCode
	}
	return ""
}

func (x *ResponseProductCodes) GetTimezoneTimeOfInterest() string {
	if x != nil && x.TimezoneTimeOfInterest != nil {
		return *x.TimezoneTimeOfInterest
	}
	return ""
}

func (x *ResponseProductCodes) GetBeginTimeOfInterestMsm() int32 {
	if x != nil && x.BeginTimeOfInterestMsm != nil {
		return *x.BeginTimeOfInterestMsm
	}
	return 0
}

func (x *ResponseProductCodes) GetEndTimeOfInterestMsm() int32 {
	if x != nil && x.EndTimeOfInterestMsm != nil {
		return *x.EndTimeOfInterestMsm
	}
	return 0
}

var File_response_product_codes_proto protoreflect.FileDescriptor

var file_response_product_codes_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x74, 0x69, 0x22, 0xbb, 0x03, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0b,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0xe3, 0xb6, 0x09, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x98, 0x8d, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x12,
	0x72, 0x71, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x9c, 0x8d, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x71, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x72,
	0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x9e, 0x8d, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x95, 0xdc, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0xa3, 0x8d, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x8d, 0x93, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x19,
	0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x66,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x18, 0xba, 0xb8, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x16, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4f,
	0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x1a, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x6d, 0x18, 0xb8, 0xb8, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x16, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x6d, 0x12, 0x38, 0x0a, 0x18, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x5f,
	0x6d, 0x73, 0x6d, 0x18, 0xb9, 0xb8, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x4d, 0x73,
	0x6d,
}

var (
	file_response_product_codes_proto_rawDescOnce sync.Once
	file_response_product_codes_proto_rawDescData = file_response_product_codes_proto_rawDesc
)

func file_response_product_codes_proto_rawDescGZIP() []byte {
	file_response_product_codes_proto_rawDescOnce.Do(func() {
		file_response_product_codes_proto_rawDescData = protoimpl.X.CompressGZIP(file_response_product_codes_proto_rawDescData)
	})
	return file_response_product_codes_proto_rawDescData
}

var file_response_product_codes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_product_codes_proto_goTypes = []interface{}{
	(*ResponseProductCodes)(nil), // 0: rti.ResponseProductCodes
}
var file_response_product_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_product_codes_proto_init() }
func file_response_product_codes_proto_init() {
	if File_response_product_codes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_response_product_codes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseProductCodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_response_product_codes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_product_codes_proto_goTypes,
		DependencyIndexes: file_response_product_codes_proto_depIdxs,
		MessageInfos:      file_response_product_codes_proto_msgTypes,
	}.Build()
	File_response_product_codes_proto = out.File
	file_response_product_codes_proto_rawDesc = nil
	file_response_product_codes_proto_goTypes = nil
	file_response_product_codes_proto_depIdxs = nil
}
